alias vi='vim'
alias la='ls -A'
alias l='ls -CF'
alias ll='ls -alFh'
alias grep='grep --color=always'
alias egrep='egrep --color=auto'
alias emacs='emacs -nw'
alias elisp='emacs -Q --script'
alias du0='du --max-depth=0 . -lh'
alias du1='du --max-depth=1 . -lh'
alias du2='du --max-depth=2 . -lh'
alias pdf='evince'

# for git
alias gitc='git checkout '
alias gc='git commit -am '
alias gm='git merge '
alias gs='git status '
alias ga='git add -A '
alias gp='git push'
alias gl='git pull'
